version: "3.3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_el_olivar
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data: